name: Déployer sur GitHub Pages
on:
  push:
    branches: [main]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  test : 
    runs-on : ubuntu-latest 
    steps : 
      - name : Récupérer le code 
        uses : actions/checkout@v4 

      - name : Installation Node 
        uses : actions/setup-node@v4
        with: 
          node-version: '20'

      - name : Initialisation 
        run : npm init -y 

      - name : Installer les dépendances 
        run : npm install 

      - name : Utiliser Lint 
        run : npm run lint

      - name : Lancer les tests 
        run : npm test 
  deploy:
    runs-on: ubuntu-latest
    needs : test 
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4
      - name: Configurer GitHub Pages
        uses: actions/configure-pages@v4
      - name: Uploader les fichiers
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'
      - name: Déployer sur GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
  check : 
    runs-on : ubuntu-latest 
    needs : deploy
    steps : 
      - name: Attendre que le site soit prêt
        run: sleep 3
      - name: Vérifier que le restaurant est ouvert
        run: |
          curl --fail https://${{ secrets.USERNAME }}.github.io/${{ secrets.REPO_NAME }} || exit 1
          echo "Le restaurant est ouvert !"

  notif : 
    needs : check 
    runs-on : ubuntu-latest 
    steps : 
    - name : url 
      run : | 
        echo "URL : https://${{ secrets.USERNAME }}.github.io/${{ secrets.REPO_NAME }}";
    - name : date  
      run : | 
        echo "Date : ${date}";
    - name : author 
      run : | 
        echo "Author : ${{ github.actor  }}";
    - name : num  
      run : | 
        echo "Commit number : ${{ github.sha }}";
    - name : msg 
      run : | 
        echo "Message : ${{ github.event.head_commit.message }}";
    - name : branch 
      run : | 
        echo "Branch : ${{ github.head_ref  }}";
      shell: bash
