name : resto2

on : 
  push : 
    branches : [main]
jobs : 
  exo : 
    runs-on : ubuntu-latest 
    steps : 

      - name : Installation Node 
        uses : actions/setup-node@v4
        with: 
          node-version: '20'
          
      - name : Initialisation 
        run : npm init -y 

      - name : Installer les d√©pendances 
        run : npm install --save-dev jest

      - name : Lancer les tests 
        run : npm test 