name : resto2

on : 
  push : 
    branches : [main]
jobs : 
  exo : 
    runs-on : ubuntu-latest 
    steps : 

      - name : Récupérer le code 
        uses : actions/checkout@v4 

      - name : Installation Node 
        uses : actions/setup-node@v4
        with: 
          node-version: '20'

      - name : Initialisation 
        run : npm init -y 

      - name : Installer les dépendances 
        run : npm install --save-dev jest

      - name : Installer les dépendances 
        run : npm install --save-dev eslint @eslint/js globals

      - name : Lint 
        run : npm run lint

      - name : Lancer les tests 
        run : npm test 